chapter1/urls.py
from django.contrib import admin
from django.urls import path, include
from pages.views import home_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),

    path('', home_view, name='home'),

    path('exams/', include('exams.urls')),

]

exams/urls.py
from django.urls import path
from exams.views import (add_task_to_exam_form, assignment_complete, assignment_details, 
                         assign_exam_form, assignments_list, archive_exam, exams_list, solution_edit)

app_name = 'exams'
urlpatterns = [
    path('', exams_list, name='exams-list'),
    path('<int:id>/', add_task_to_exam_form, name='exam-detail'),
    path('<int:id>/assign', assign_exam_form, name='exam-assign'),
    path('<int:id>/archive', archive_exam, name='exam-archive'),

    path('assignments', assignments_list, name='assignments-list'),
    path('assignment_details/<int:id>', assignment_details, name='assignment-details'),
    path('assignment_complete/<int:id>', assignment_complete, name='assignment-complete'),

    path('solution/<int:id>', solution_edit, name='solution-edit')
]

exams/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class Exam(models.Model):
    name = models.CharField(max_length=30)
    description = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    archived = models.BooleanField(default=False)

    def absoluteURL(self):
        return reverse('exams:exam-detail', kwargs={'id': self.id})

    def assignURL(self):
        return reverse('exams:exam-assign', kwargs={'id': self.id})

    def archiveURL(self):
        return reverse('exams:exam-archive', kwargs={'id': self.id})

class Task(models.Model):
    task = models.TextField()
    score = models.IntegerField()
    exam = models.ForeignKey(Exam, on_delete=models.CASCADE)

class Assignment(models.Model):
    exam = models.ForeignKey(Exam, on_delete=models.CASCADE) 
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    grade = models.IntegerField(default=0)
    completed = models.BooleanField(default=False)

    def absoluteURL(self):
        return reverse('exams:assignment-details', kwargs={'id': self.id})

    def completeURL(self):
        return reverse('exams:assignment-complete', kwargs={'id': self.id})

class Solution(models.Model):
    finished = models.BooleanField(default=False)
    solution = models.TextField()
    score = models.DecimalField(decimal_places=2, max_digits=100, default=0)
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    assignment = models.ForeignKey(Assignment, on_delete=models.CASCADE)

    def editURL(self):
        return reverse('exams:solution-edit', kwargs={'id': self.id})

pages/models.py
from django.db import models

# Create your models here.

exams/forms.py
from django import forms

from .models import Exam, Task, Assignment, Solution

class ExamForm(forms.ModelForm):
    class Meta:
        model = Exam
        fields = [
            'name',
            'description'
        ]

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = [
            'task',
            'score'
        ]

class AssignmentForm(forms.ModelForm):
    class Meta:
        model = Assignment
        fields = [
            'user',
        ]

class SolutionForm(forms.ModelForm):
    class Meta:
        model = Solution
        fields = [
            'solution',
        ]

exams/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import Http404
from django.contrib.auth.decorators import login_required

from .models import Exam, Task, Assignment, Solution
from .forms import ExamForm, TaskForm, AssignmentForm, SolutionForm

# Create your views here.

@login_required
def exams_list(request):
    if not request.user.has_perm('exams.add_exam'):
        raise Http404
    exams = Exam.objects.filter(user=request.user, archived=False)
    form = ExamForm(request.POST or None)
    if form.is_valid():
        form = form.save(commit=False)
        form.user = request.user
        form.save()
        form = ExamForm()

    context = {
        'exams': exams,
        'form': form
    }

    return render(request, 'exam/list.html', context)

@login_required
def assignments_list(request):
    assignments = Assignment.objects.filter(user=request.user)

    context = {
        'assignments': assignments
    }

    return render(request, 'assignments/list.html', context)

@login_required
def add_task_to_exam_form(request, id):
    if not request.user.has_perm('exams.add_task'):
        raise Http404
    exam = get_object_or_404(Exam, id=id, archived=False)
    tasks = Task.objects.filter(exam=exam)
    form = TaskForm(request.POST or None)
    if form.is_valid():
        form = form.save(commit=False)
        form.exam = exam
        form.save()
        form = TaskForm()

    context = {
        'exam': exam,
        'tasks': tasks,
        'form': form
    }

    return render(request, 'exam/detail.html', context)  

@login_required
def assign_exam_form(request, id):
    if not request.user.has_perm('exam.add_assignment'):
        raise Http404
    exam = get_object_or_404(Exam, id=id, archived=False)
    tasks = Task.objects.filter(exam=id)
    assignments = Assignment.objects.filter(exam=id)
    form = AssignmentForm(request.POST or None)
    if form.is_valid():
        form = form.save(commit=False)
        form.exam = exam
        form.save()
        for task in tasks:
            solution = Solution.objects.create(solution='', task=task, score=0, assignment=form)
            solution.save()
        form = AssignmentForm()

    context = {
        'exam': exam,
        'assignments': assignments,
        'form': form
    }

    return render(request, 'exam/assign.html', context)

@login_required
def archive_exam(request, id):
    if not request.user.has_perm('exams.add_exam'):
        raise Http404
    exam = get_object_or_404(Exam, id=id, archived=False, user=request.user)
    if request.method == 'POST':
        exam.archived = True
        exam.save()
        return redirect('../')

    context = {
        'exam': exam,
    }

    return render(request, 'exam/archive.html', context)

@login_required
def assignment_details(request, id):
    assignment = get_object_or_404(Assignment, id=id)
    if not assignment.user == request.user:
        raise Http404
    solutions = Solution.objects.filter(assignment=assignment)

    context = {
        'assignment': assignment,
        'solutions': solutions
    }

    return render(request, 'assignments/details.html', context)

@login_required
def solution_edit(request, id):
    solution = get_object_or_404(Solution, id=id)
    if not solution.assignment.user == request.user:
        raise Http404
    if solution.task.exam.archived or solution.assignment.completed:
        raise Http404
    form = SolutionForm(request.POST or None, instance=solution)
    if form.is_valid():
        form.finished = True
        form.save()
        return redirect('../assignment_details/'+str(solution.assignment.id))

    context = {
        'solution': solution,
        'form': form,
    }

    return render(request, 'assignments/edit.html', context)

@login_required
def assignment_complete(request, id):
    assignment = get_object_or_404(Assignment, id=id)
    if not assignment.user == request.user:
        raise Http404
    if assignment.exam.archived or assignment.completed:
        raise Http404
    if request.method == 'POST':
        assignment.completed = True
        assignment.save()
        return redirect('../assignments')

    context = {
        'assignment': assignment,
    }

    return render(request, 'assignments/complete.html', context)

pages/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def home_view(request, *args, **kwargs):
    return render(request, 'home.html', {})

exams/templates/assignments/complete.html
{% extends 'base.html' %}

{% block content %}

<h1>Are you sure that you want to complete your assignment?</h1>
<form method='POST'> 
        {% csrf_token %}
        {{ form.as_p }}
        <input type='submit' value='COMPLETE' />

</form>
{% endblock %}

exams/templates/assignments/details.html
{% extends 'base.html' %}

{% block content %}
<h1>Exam: {{ assignment.exam.name }}</h1>
<hx>Questions:</hx>
<ul>
    {% for s in solutions %}
        <li>Tasks: {{ forloop.counter }}</li>
            <ul>
                <li>Task: {{ s.task.task }}</li>
                <li>Solution: {{ s.solution }}</li>
                {% if not s.task.exam.archived and not s.assignment.completed %}
                    <li><a href="{{ s.editURL }}">EDIT</a></li>
                {% endif %}
            </ul>
        </li>
    {% endfor %}
</ul>
{% if not assignment.completed %}
<a href="{{ assignment.completeURL }}">COMPLETE EXAM</a>
{% endif %}
{% endblock %}

exams/templates/assignments/edit.html
{% extends 'base.html' %}

{% block content %}
<h1>Task: {{ solution.task.task }}</h1>
<h1>Solution:</h1>
<form method='POST'> 
        {% csrf_token %}
        {{ form.as_p }}
        <input type='submit' value='Save' />
</form>
{% endblock %}

exams/templates/assignments/list.html
{% extends 'base.html' %}

{% block content %}
<h1>Assignments:</h1>
<ul>
    {% for a in assignments %}
        {% if not a.exam.archived and not a.completed %}
            <li>ACTIVE <a href="{{ a.absoluteURL }}">{{ a.exam.name }}</a> 
        {% elif not a.exam.archived and a.completed %}
            <li>COMPLETED <a href="{{ a.absoluteURL }}">{{ a.exam.name }}</a> 
        {% elif a.exam.archived %}
            <li>ARCHIVED <a href="{{ a.absoluteURL }}">{{ a.exam.name }}</a>
        {% endif %}
        </li>
    {% endfor %}
</ul>
{% endblock %}

exams/templates/exam/archive.html
{% extends 'base.html' %}

{% block content %}

<h1>Are you sure that you want to archive Exam</h1>
<form method='POST'> 
        {% csrf_token %}
        {{ form.as_p }}
        <input type='submit' value='ARCHIVE' />

</form>
{% endblock %}

exams/templates/exam/assign.html
{% extends 'base.html' %}

{% block content %}

<h1>Exam: {{ exam.name }}</h1>
<hx>Assigned:</hx>
<ul>
    {% for a in assignments %}
        <li>{{ a.user }}</li> 
    {% endfor %}
</ul>

<h1>Add task</h1>
<form method='POST'> 
        {% csrf_token %}
        {{ form.as_p }}
        <input type='submit' value='Save' />

</form>
{% endblock %}

exams/templates/exam/detail.html
{% extends 'base.html' %}

{% block content %}
<h1>Exam: {{ exam.name }}</h1>
<hx>Questions:</hx>
<ul>
    {% for t in tasks %}
        <li>Tasks: {{ forloop.counter }}</li>
            <ul>
                <li>{{ t.task }}</li>
                <li>Max score: {{ t.score }}</li>
            </ul>
        </li>
    {% endfor %}
</ul>

<h1>Add task</h1>
<form method='POST'> 
        {% csrf_token %}
        {{ form.as_p }}
        <input type='submit' value='Save' />
</form>
{% endblock %}

exams/templates/exam/list.html
{% extends 'base.html' %}

{% block content %}
<h1>Add new exam:</h1>
<form method='POST'> {% csrf_token %}
        {{ form.as_p }}
        <input type='submit' value='Save' />
</form>
<hx>Exams:</hx>
<ul>
    {% for e in exams %}
        <li><a href="{{ e.absoluteURL }}">{{ e.name }}</a> 
            <a href="{{ e.assignURL }}">assign</a>
            <a href="{{ e.archiveURL }}">ARCHIVE</a>
        </li>
    {% endfor %}
</ul>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>SG</title>
    </head>
    <body>
        {% include 'navigation.html' %}
        {% block content %}
        {% endblock %}
    </body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}
    {% if user.is_authenticated %}
        Hi {{ user.username }}!
        <p><a href="{% url 'logout' %}">logout</a></p>
    {% else %}
        <p>You are not logged in</p>
        <a href="{% url 'login' %}">login</a>
    {% endif %}
{% endblock %}

templates/navigation.html
<nav>
    <ul>
        <li><a href="{% url 'home' %}">Home</a></li>
        <li><a href="{% url 'exams:exams-list' %}">Exams</a></li>
        <li><a href="{% url 'exams:assignments-list' %}">Assignments</a></li>
    </ul>
</nav>